# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-01-26 12:06:11
"""
import arcpy

def CreateWorkingGDBsandFolders():  # CreateWorkingGDBsandFolders

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
        Folder_Location = "F:"

        # Process: Create Folder (Create Folder) (management)
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
            ModelFiles = arcpy.management.CreateFolder(out_folder_path=Folder_Location, out_name="ModelFiles")[0]

        # Process: Create Folder (2) (Create Folder) (management)
        if ModelFiles:
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
                SilviculturalSites = arcpy.management.CreateFolder(out_folder_path=ModelFiles, out_name="SilviculturalSites")[0]

        # Process: Create Folder (6) (Create Folder) (management)
        if ModelFiles:
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
                Output_Folder_3_ = arcpy.management.CreateFolder(out_folder_path=SilviculturalSites, out_name="IntermediateSilvicultureFiles")[0]

        # Process: Create Folder (10) (Create Folder) (management)
        if ModelFiles:
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
                SiteHistory = arcpy.management.CreateFolder(out_folder_path=Output_Folder_3_, out_name="SiteHistory")[0]

        # Process: Create File Geodatabase (Create File Geodatabase) (management)
        if ModelFiles:
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
                FinalSilviculturalSiteHistoryGDB_gdb = arcpy.management.CreateFileGDB(out_folder_path=SiteHistory, out_name="FinalSilviculturalSiteHistoryGDB", out_version="CURRENT")[0]

        # Process: Create File Geodatabase (2) (Create File Geodatabase) (management)
        if ModelFiles:
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
                IntermediateSiteHistoryFiles_gdb = arcpy.management.CreateFileGDB(out_folder_path=SiteHistory, out_name="IntermediateSiteHistoryFiles", out_version="CURRENT")[0]

        # Process: Create Folder (5) (Create Folder) (management)
        if ModelFiles:
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
                Output_Folder_2_ = arcpy.management.CreateFolder(out_folder_path=SilviculturalSites, out_name="FinalSilviculturalSitesForAnalysis")[0]

        # Process: Create Folder (12) (Create Folder) (management)
        if ModelFiles:
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
                FinalSilviculturalSitesForAnalysis_Shapefiles = arcpy.management.CreateFolder(out_folder_path=Output_Folder_2_, out_name="FinalSilviculturalSitesForAnalysis_Shapefiles")[0]

        # Process: Create File Geodatabase (5) (Create File Geodatabase) (management)
        if ModelFiles:
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
                FinalSilviculturalSitesForAnalysis_GDB_gdb = arcpy.management.CreateFileGDB(out_folder_path=Output_Folder_2_, out_name="FinalSilviculturalSitesForAnalysis_GDB", out_version="CURRENT")[0]

        # Process: Create Folder (8) (Create Folder) (management)
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
            OriginalFiles = arcpy.management.CreateFolder(out_folder_path=ModelFiles, out_name="OriginalFiles")[0]

        # Process: Create File Geodatabase (4) (Create File Geodatabase) (management)
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
            OriginalFiles_gdb = arcpy.management.CreateFileGDB(out_folder_path=OriginalFiles, out_name="OriginalFiles", out_version="CURRENT")[0]

        # Process: Create Folder (11) (Create Folder) (management)
        if ModelFiles:
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
                AdditionalSelectionParameters = arcpy.management.CreateFolder(out_folder_path=Output_Folder_3_, out_name="AdditionalSelectionParameters")[0]

        # Process: Create Folder (9) (Create Folder) (management)
        if ModelFiles:
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
                Output_Folder_5_ = arcpy.management.CreateFolder(out_folder_path=AdditionalSelectionParameters, out_name="Buffer")[0]

        # Process: Create File Geodatabase (6) (Create File Geodatabase) (management)
        if ModelFiles:
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
                FinalSilviculturalBufferFiles_gdb = arcpy.management.CreateFileGDB(out_folder_path=Output_Folder_5_, out_name="FinalSilviculturalBufferFiles", out_version="CURRENT")[0]

        # Process: Create File Geodatabase (7) (Create File Geodatabase) (management)
        if ModelFiles:
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
                IntermediateSilviculturalBufferFiles_gdb = arcpy.management.CreateFileGDB(out_folder_path=Output_Folder_5_, out_name="IntermediateSilviculturalBufferFiles", out_version="CURRENT")[0]

        # Process: Create File Geodatabase (8) (Create File Geodatabase) (management)
        if ModelFiles:
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
                EliminatedSiteHistoryFiles_gdb = arcpy.management.CreateFileGDB(out_folder_path=SiteHistory, out_name="EliminatedSiteHistoryFiles", out_version="CURRENT")[0]

        # Process: Create Folder (13) (Create Folder) (management)
        if ModelFiles:
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
                Output_Folder_6_ = arcpy.management.CreateFolder(out_folder_path=AdditionalSelectionParameters, out_name="RelativeLocation")[0]

        # Process: Create File Geodatabase (9) (Create File Geodatabase) (management)
        if ModelFiles:
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
                FinalSilviculturalRelativeLocationFiles_gdb = arcpy.management.CreateFileGDB(out_folder_path=Output_Folder_6_, out_name="FinalSilviculturalRelativeLocationFiles", out_version="CURRENT")[0]

        # Process: Create File Geodatabase (10) (Create File Geodatabase) (management)
        if ModelFiles:
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
                IntermediateSilviculturalRelativeLocationFiles_gdb = arcpy.management.CreateFileGDB(out_folder_path=Output_Folder_6_, out_name="IntermediateSilviculturalRelativeLocationFiles", out_version="CURRENT")[0]

        # Process: Create File Geodatabase (11) (Create File Geodatabase) (management)
        if ModelFiles:
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
                FinalSilviculturalSiteHistorySPLIT_gdb = arcpy.management.CreateFileGDB(out_folder_path=SiteHistory, out_name="FinalSilviculturalSiteHistorySPLIT", out_version="CURRENT")[0]

if __name__ == '__main__':
    CreateWorkingGDBsandFolders()
