# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-01-26 12:07:05
"""
import arcpy
import os

def FeatureClassGenerator(workspace, wild_card, feature_type, recursive) :
  with arcpy.EnvManager(workspace = workspace):

    dataset_list = [""]
    if recursive:
      datasets = arcpy.ListDatasets()
      dataset_list.extend(datasets)

    for dataset in dataset_list:
      featureclasses = arcpy.ListFeatureClasses(wild_card, feature_type, dataset)
      for fc in featureclasses:
        yield os.path.join(workspace, dataset, fc), fc

def #  NOT  IMPLEMENTED# Function Body not implemented

def SilviculturalSites_AdditionalParameters_Buffer():  # SilviculturalSites_AdditionalParameters_Buffer

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Data Management Tools.tbx")
    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Conversion Tools.tbx")
    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
        FinalSilviculturalRelativeLocationFiles_gdb = "F:\\ModelFiles\\SilviculturalSites\\IntermediateSilvicultureFiles\\AdditionalSelectionParameters\\RelativeLocation\\FinalSilviculturalRelativeLocationFiles.gdb"
        False_72 = False
        FinalSilviculturalSitesForAnalysis_Shapefiles_2_ = "F:\\ModelFiles\\SilviculturalSites\\FinalSilviculturalSitesForAnalysis\\FinalSilviculturalSitesForAnalysis_Shapefiles"
        BatchForestrySiteSelectionParameters_Project_Buffer_Insecticide_Fire_Shapefiles_2_ = "F:\\Masters Data- Chapter 2\\BatchForestrySiteSelectionParameters-Project_Buffer_Insecticide_Fire__Shapefiles"
        FinalSilviculturalSiteHistoryGDB_gdb = "F:\\ModelFiles\\SilviculturalSites\\IntermediateSilvicultureFiles\\SiteHistory\\FinalSilviculturalSiteHistoryGDB.gdb"

        for FeatureClass, Name in FeatureClassGenerator(FinalSilviculturalRelativeLocationFiles_gdb, "", "", "NOT_RECURSIVE"):

            # Process: Project (Project) (management)
            Name = "FeatureClass"
            _Name_MOD1 = fr"F:\ModelFiles\SilviculturalSites\IntermediateSilvicultureFiles\AdditionalSelectionParameters\Buffer\IntermediateSilviculturalBufferFiles.gdb\{Name}MOD1"
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
                arcpy.management.Project(in_dataset=FeatureClass, out_dataset=_Name_MOD1, out_coor_system="PROJCS[\"Canada_Albers_Equal_Area_Conic\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Albers\"],PARAMETER[\"False_Easting\",0.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-96.0],PARAMETER[\"Standard_Parallel_1\",50.0],PARAMETER[\"Standard_Parallel_2\",70.0],PARAMETER[\"Latitude_Of_Origin\",40.0],UNIT[\"Meter\",1.0]]", transform_method=[], in_coor_system="", preserve_shape="NO_PRESERVE_SHAPE", max_deviation="", vertical="NO_VERTICAL")

            # Process: Buffer (Buffer) (analysis)
            _Name_MOD2 = fr"F:\ModelFiles\SilviculturalSites\IntermediateSilvicultureFiles\AdditionalSelectionParameters\Buffer\IntermediateSilviculturalBufferFiles.gdb\{Name}MOD2"
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
                arcpy.analysis.Buffer(in_features=_Name_MOD1, out_feature_class=_Name_MOD2, buffer_distance_or_field="-60 Meters", line_side="FULL", line_end_type="ROUND", dissolve_option="NONE", dissolve_field=[], method="PLANAR")

            # Process: Copy Features (4) (Copy Features) (management)
            _Name_MOD2a = fr"F:\ModelFiles\SilviculturalSites\IntermediateSilvicultureFiles\AdditionalSelectionParameters\Buffer\IntermediateSilviculturalBufferFiles.gdb\{Name}MOD2a"
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
                arcpy.management.CopyFeatures(in_features=_Name_MOD2, out_feature_class=_Name_MOD2a, config_keyword="", spatial_grid_1=None, spatial_grid_2=None, spatial_grid_3=None)

            # Process: Get Count (Get Count) (management)
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
                Row_Count = arcpy.management.GetCount(in_rows=_Name_MOD2a)[0]

            # Process: If Row Count Is (If Row Count Is) ()
            if int(Row_Count):
                with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
                    True_104, False_2_ = #  NOT  IMPLEMENTED(in_layer_or_view=_Name_MOD2a, count_condition="IS_NOT_EQUAL_TO", count=0, count_min=0, count_max=0)

            # Process: Add Fields (multiple) (4) (Add Fields (multiple)) (management)
            if False_72 and int(Row_Count) and True_104:
                with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
                    _Name_MOD2_3_ = arcpy.management.AddFields(in_table=_Name_MOD2a, field_description=[["Perimeter_Canada_Albers_EqualAreamNeg60mBuffer", "DOUBLE", "Perimiter (m)", "", "", ""], ["Area_Canada_Albers_EqualAream2Neg60mBuffer", "DOUBLE", "Area (m2)", "", "", ""], ["Perimiter_Area_RatioNeg60mBuffer", "DOUBLE", "P/A", "", "", ""]])[0]

            # Process: Calculate Geometry Attributes (Calculate Geometry Attributes) (management)
            if False_72 and int(Row_Count) and True_104:
                with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
                    _Name_MOD2_4_ = arcpy.management.CalculateGeometryAttributes(in_features=_Name_MOD2_3_, geometry_property=[["Perimeter_Canada_Albers_EqualAreamNeg60mBuffer", "PERIMETER_LENGTH"], ["Area_Canada_Albers_EqualAream2Neg60mBuffer", "AREA"]], length_unit="METERS", area_unit="SQUARE_METERS", coordinate_system="PROJCS[\"Canada_Albers_Equal_Area_Conic\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Albers\"],PARAMETER[\"False_Easting\",0.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-96.0],PARAMETER[\"Standard_Parallel_1\",50.0],PARAMETER[\"Standard_Parallel_2\",70.0],PARAMETER[\"Latitude_Of_Origin\",40.0],UNIT[\"Meter\",1.0]]", coordinate_format="SAME_AS_INPUT")[0]

            # Process: Calculate Field (19) (Calculate Field) (management)
            if False_72 and int(Row_Count) and True_104:
                with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
                    _Name_MOD2_5_ = arcpy.management.CalculateField(in_table=_Name_MOD2_4_, field="Perimiter_Area_RatioNeg60mBuffer", expression="!Perimeter_Canada_Albers_EqualAreamNeg60mBuffer!/!Area_Canada_Albers_EqualAream2Neg60mBuffer!", expression_type="PYTHON3", code_block="", field_type="TEXT", enforce_domains="NO_ENFORCE_DOMAINS")[0]

            # Process: Copy Features (Copy Features) (management)
            _Name_shp = fr"F:\ModelFiles\SilviculturalSites\IntermediateSilvicultureFiles\AdditionalSelectionParameters\Buffer\{Name}.shp"
            if False_72 and int(Row_Count) and True_104:
                with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
                    arcpy.management.CopyFeatures(in_features=_Name_MOD2_5_, out_feature_class=_Name_shp, config_keyword="", spatial_grid_1=None, spatial_grid_2=None, spatial_grid_3=None)

            # Process: Feature Class To Shapefile (Feature Class To Shapefile) (conversion)
            if False_72 and int(Row_Count) and True_104:
                with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
                    FinalSilviculturalSitesForAnalysis_Shapefiles = arcpy.conversion.FeatureClassToShapefile(Input_Features=[_Name_shp], Output_Folder=FinalSilviculturalSitesForAnalysis_Shapefiles_2_)[0]

            # Process: Delete (Delete) (management)
            if False_2_ and int(Row_Count):
                with arcpy.EnvManager(scratchWorkspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb", workspace=r"C:\Users\heath\Downloads\Masters Data- Chapter 2\Masters Data- Chapter 2\Default.gdb"):
                    Delete_Succeeded = arcpy.management.Delete(in_data=[_Name_MOD2, _Name_MOD2a], data_type="")[0]

if __name__ == '__main__':
    SilviculturalSites_AdditionalParameters_Buffer()
